[package]
name = "malta"
version = "0.1.0"
edition = "2021"

[dependencies]
malta-core = { path = "malta-core" }
# xilem = { git = "https://github.com/linebender/xilem/", version = "0.1.0" }

[workspace]
members = [
    "malta-core",
    "malta-web"
]
