[package]
name = "malta"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.0", features = ["sqlite", "time"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
libsqlite3-sys = { version = "0.28.0", features = ["bundled"] }
once_cell = "1.19.0"
time = "0.3.36"
xilem = { git = "https://github.com/linebender/xilem/", version = "0.1.0" }
