[package]
name = "malta"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
once_cell = "1.19.0"
time = "0.3.36"
xilem = { git = "https://github.com/linebender/xilem/", version = "0.1.0" }

[dependencies.gluesql]
version = "0.15.0"
default-features = false
features = ["sled-storage"]
