[package]
name = "malta"
version = "0.1.0"
edition = "2021"

[dependencies]
iced_aw = "0.9.3"
rusqlite = { version = "0.31.0", features = ["bundled"] }

[dependencies.iced]
version = "0.12.1"
features = ["advanced", "image"]
