pub use windows::Win32::Graphics::Gdi::{
    COLOR_3DFACE, COLOR_3DHILIGHT, COLOR_3DLIGHT, COLOR_3DSHADOW, COLOR_BTNFACE, COLOR_BTNSHADOW,
    COLOR_BTNTEXT, COLOR_DESKTOP, COLOR_GRAYTEXT, COLOR_HIGHLIGHT, COLOR_HOTLIGHT, COLOR_INFOBK,
    COLOR_INFOTEXT, COLOR_MENU, COLOR_MENUBAR, COLOR_MENUTEXT, COLOR_SCROLLBAR, COLOR_WINDOW,
};
